%%{ init: {'theme': 'neutral' , "themeVariables": { "fontSize": "20px"}}}%%
flowchart TD
    B[fa:fa-user user]
    B-->C[fa:fa-ban forbidden]
    B-->D[fa:fa-spinner spinner]
    B-->E[fa:fa-camera-retro camera]